### ISSUE TITLE
postcss-import 

### ISSUE THREAD

**Issue by OmelyanenkoV** [Innei/naive-ui-dashboard-template#242]
There is a postcss import dependency in the project, but I don't understand where it is being included. File postcss.config.js - empty

**Comment by Innei** [comment]
> There is a postcss import dependency in the project, but I don't understand where it is being included. File postcss.config.js - empty

@OmelyanenkoV Yep, you are right. This is only used by tailwindcss. But now I migrate to windicss so it is not necessary. I will remove it. Thanks for your issue.
